
import java.io.File;
import java.util.LinkedList;
import java.util.Scanner;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Courtney
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        student = new javax.swing.JRadioButton();
        company = new javax.swing.JRadioButton();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        loginButton2 = new javax.swing.JButton();
        textFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(871, 536));

        student.setBackground(new java.awt.Color(255, 255, 255));
        userType.add(student);
        student.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        student.setSelected(true);
        student.setText("Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });

        company.setBackground(new java.awt.Color(255, 255, 255));
        userType.add(company);
        company.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        company.setText("Company");
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        emailLabel.setText("Email");

        passwordLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        passwordLabel.setText("Password");

        loginButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("JOBS");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("WARRINGTON");

        registerButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        loginButton2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        loginButton2.setText("Report");
        loginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton2ActionPerformed(evt);
            }
        });

        textFile.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        textFile.setText("Read from Text File");
        textFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginButton2)
                .addGap(371, 371, 371))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(student)
                                .addGap(18, 18, 18)
                                .addComponent(company))
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(passwordTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(loginButton)
                                .addGap(27, 27, 27)
                                .addComponent(registerButton))
                            .addComponent(textFile))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company)
                    .addComponent(student))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(registerButton))
                .addGap(18, 18, 18)
                .addComponent(loginButton2)
                .addGap(18, 18, 18)
                .addComponent(textFile)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if(student.isSelected())
        {
            RegisterStudent rs = new RegisterStudent();
            rs.setVisible(true);
            this.dispose();
        }
        else
        {
            RegisterNewCompany rnc = new RegisterNewCompany();
            rnc.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String email = emailTextField.getText();
        String password = passwordTextField.getText();
        if(student.isSelected())
        {
           boolean credentials = JobSearchSystem.checkCredentials(email, password, "student");
           if(credentials)
           {
               Student student =JobSearchSystem.getStudentByEmail(email);
               StudentSearchJobGUI ssjg = new StudentSearchJobGUI(student);
               ssjg.setVisible(true);
               this.dispose();
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Incorrect email or password");
           }
    
        }
        
         if(company.isSelected())
        {
           boolean credentials = JobSearchSystem.checkCredentials(email, password, "company");
           if(credentials)
           {
               Company company = JobSearchSystem.getCompanyByEmail(email);
               CompanyPageGUI cpg = new CompanyPageGUI(company);
               cpg.setVisible(true);
               setVisible(false);
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Incorrect email or password");
           }
    
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton2ActionPerformed
        // TODO add your handling code here:
        Report g = new Report();
        g.setVisible(true);
    }//GEN-LAST:event_loginButton2ActionPerformed

    private void textFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFileActionPerformed
                Scanner s1 = null, s2 = null, s3=null, s4=null, s5=null; File file;
        try {
            
            
            File f2 = new File("companies.txt");
            s2 = new Scanner(f2);
            
            while(s2.hasNextLine()) {
                String line = s2.nextLine();
                String[] compInfo = line.split(",");
                    JobSearchSystem.addNewCompany(new Company(compInfo[0], compInfo[1], compInfo[2]));
            }
            
            File f3 = new File("jobs.txt");
            s3 = new Scanner(f3);
            
            while(s3.hasNextLine()) {
                String line = s3.nextLine();
                String[] jobInfo = line.split(",,");
                int companyID = Integer.parseInt(jobInfo[0]);
                Company comp =JobSearchSystem.getCompanyById(companyID);
                comp.addJobs(new Job(jobInfo[1], jobInfo[2], jobInfo[3], jobInfo[4], jobInfo[5], jobInfo[6], jobInfo[7], jobInfo[8]));
            }  
            
            File f1 = new File("students.txt");
            s1 = new Scanner(f1);
              String[] adds;
            while(s1.hasNextLine()) {
                String line = s1.nextLine();
                String[] cInfo = line.split(",");
                if(cInfo[0].equals("U"))
                {
                    file = new File(cInfo[7]);
                   
     
                    Student s = new Undergraduate(Integer.parseInt(cInfo[1]), cInfo[2], cInfo[3], cInfo[4], Integer.parseInt(cInfo[5]), cInfo[6], file,Double.parseDouble(cInfo[8]), cInfo[9]);
                    JobSearchSystem.addNewStudent(s);
                     if(cInfo.length == 11)
                    {
                      adds = cInfo[10].split(" ");
                      for(int j =0; j < adds.length; j++)
                     {
                     Job jj = JobSearchSystem.getJobById(Integer.parseInt(adds[j]));
                     s.addJob(jj);
                     }
                     
                         
                     }
                    
                    //s.addJob(job);
                     }  
            
                
                else
                {
                    file = new File(cInfo[7]);
                    Student g = new Graduate(Integer.parseInt(cInfo[1]), cInfo[2], cInfo[3], cInfo[4], Integer.parseInt(cInfo[5]), cInfo[6], file,Double.parseDouble(cInfo[8]), cInfo[9], cInfo[10], Double.parseDouble(cInfo[11]));
                    JobSearchSystem.addNewStudent(g);   
                   if(cInfo.length == 13)
                    {
                      adds = cInfo[12].split(" ");
                      System.out.println(adds.length);
                      for(int j =0; j < adds.length; j++)
                     {
                     Job jj = JobSearchSystem.getJobById(Integer.parseInt(adds[j]));
                     g.addJob(jj);
                     }
                     
                         
                     }
                
                
                } 
                
            }
            File f5 = new File("applications.txt");
            s5 = new Scanner(f5);
            
            while(s5.hasNextLine()) {
                String line = s5.nextLine();
                String[] appsInfo = line.split(",");
   
             //   JobSearchSystem.applytoJob(new Application());
                
                //Company comp = JobSearchSystem.getCompanyById(Integer.parseInt(appsInfo[0]));
                Job j = JobSearchSystem.getJobById(Integer.parseInt(appsInfo[0]));
                Student stu = JobSearchSystem.getStudentById(Integer.parseInt(appsInfo[1]));
               // Interview inte = JobSearchSystem.getInterviewById(Integer.parseInt(appsInfo[3]));
                JobSearchSystem.applytoJob(new Application(stu, j, appsInfo[2]));
                //comp.addJobs(new Job(jobInfo[0],jobInfo[1], jobInfo[2], jobInfo[3], jobInfo[4], jobInfo[5], jobInfo[6], jobInfo[7]));
            }    
            
            
            
            
            File f4 = new File("interviews.txt");
            s4 = new Scanner(f4);
            
            while(s4.hasNextLine()) {
                String line = s4.nextLine();
                String[] interviewsInfo = line.split(",");
                Job j = JobSearchSystem.getJobById(Integer.parseInt(interviewsInfo[0]));
                Student stu = JobSearchSystem.getStudentById(Integer.parseInt(interviewsInfo[1]));
                Application app = JobSearchSystem.getApplication(stu, j);
               // Company comp =JobSearchSystem.getCompanyById(companyID);
               app.setInterview(new Interview(interviewsInfo[2], Integer.parseInt(interviewsInfo[3])));
               // comp.addJobs(new Job(jobInfo[0],jobInfo[1], jobInfo[2], jobInfo[3], jobInfo[4], jobInfo[5], jobInfo[6], jobInfo[7]));
            }    
        } catch (Exception e) {
            System.out.println(e.toString());
        } finally {
            if(s1 != null) s1.close();
            if(s2 != null) s2.close();
        }
    }//GEN-LAST:event_textFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>
           
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton company;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton loginButton2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JRadioButton student;
    private javax.swing.JButton textFile;
    private javax.swing.ButtonGroup userType;
    // End of variables declaration//GEN-END:variables
}
